language: c
compiler:
  - gcc
  - clang
notifications:
  recipients:
    - kenhys@gmail.com
branches:
  only:
    - master
    - develop
env:
  - SYLPHEED_STAGE=master
  - SYLPHEED_STAGE=3.5.0beta1
  - SYLPHEED_STAGE=3.4.2
before_script:
  - curl https://raw.github.com/kenhys/sylpheed-plugin-factory/master/misc/setup-travis.sh | sh
  - git submodule update --init --recursive
  - ./autogen.sh
script:
  - ./configure --with-sylpheed-build-dir=`pwd`/sylpheed
  - make
